# Generated by Django 4.1.4 on 2023-03-11 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vamp_scans', '0001_initial'),
        ('vamp_exceptions', '0002_rename_exception_exceptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptions',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vamp_scans.host'),
        ),
        migrations.AlterField(
            model_name='exceptions',
            name='finding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vamp_scans.finding'),
        ),
    ]
