# Generated by Django 4.1.4 on 2023-09-02 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vamp_scans', '0004_finding_request_type'),
        ('vamp_exceptions', '0005_exceptions_approved_exceptions_still_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ignore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=2048)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ignore_approver', to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vamp_scans.finding')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vamp_scans.host')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignore_requestor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
