# Generated by Django 4.1.4 on 2023-03-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vamp_scans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='status',
            field=models.IntegerField(choices=[(0, 'open'), (1, 'patched'), (2, 'workaround'), (3, 'exception'), (4, 'false'), (5, 'ignore'), (6, 'progress')], default=0),
        ),
    ]
