# Generated by Django 4.1.4 on 2023-09-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vamp_scans', '0003_hostcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='request_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
