# Generated by Django 4.1.4 on 2023-02-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenableAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=1024)),
                ('access_key', models.CharField(max_length=200)),
                ('secret_key', models.CharField(max_length=200)),
                ('severities', models.CharField(default='', max_length=1024)),
            ],
        ),
    ]
